### ISSUE TITLE
[bib] Add bibtex entries 

### ISSUE THREAD

**Issue by at15** [at15/papers-i-read#102]
Related https://github.com/dyweb/mos/issues/25

I don't think @gaocegege would have time to that now, so I will just start from mine first and use it for my thesis (yes, it's still not finished thanks to my committee) and [Notes-On-TSDB](https://github.com/xephonhq/notes-on-tsdb)

TODO

- [ ] cite urls
  - https://engineering.purdue.edu/~mark/puthesis/faq/cite-url/
  - https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=LaTeX&id=413720397

**Comment by gaocegege** [comment]
Good luck
