### ISSUE TITLE
 Rethinking Data-Intensive Science Using Scalable Analytics Systems

### ISSUE THREAD

**Issue by at15** [at15/papers-i-read#29]
Use Spark, Parquet (column store format based on Google's Dremel paper) to replace old HPC based scientific computing pipeline. Speed up and more general using an layer model (inspired by OSI). 

It also mentioned time series data, which is a very important attribute of many scientific data, but I guess they didn't focus too much on it

Well, to be honest, I think specific system is more interesting, if I only work on genomic, why the heck would I want this system to work for other science fields, unless I want to sell this system to wide range of customers.

**Comment by gaocegege** [comment]
Admiration arises despite my incomprehension of what you said.
